#!/bin/bash

SECRET_ID="$1"

# Get the variables from Secrets Manager
aws secretsmanager get-secret-value \
    --secret-id "$SECRET_ID" \
    --query SecretString \
    --output text \
> /variables.json

# Convert the variables from the JSON to bash environment variables
jq -r "to_entries|map(\"export \(.key)=\(.value)\")|.[]" /variables.json > /variables.sh
source /variables.sh

# Write the token details to a file
echo "{\"$token_id\" : \"$token_secret\"}" > /token
