---
- name: Tableau Bridge Linux
  hosts: all
  become: true

  pre_tasks:
    - name: Update & Upgrade APT 
      apt:
        update_cache: yes
        upgrade: 'yes'

  roles:
    - geerlingguy.docker

  tasks:
    - name: Create bridge directory
      file:
        path: "/bridge"
        state: directory

    - name: Download Tableau Bridge installer
      get_url:
        url: "https://downloads.tableau.com/tssoftware/TableauBridge-20233.23.1017.0948.x86_64.rpm"
        dest: "/bridge/bridge.rpm"

    - name: Download Postgres JDBC Driver
      get_url:
        url: "https://jdbc.postgresql.org/download/postgresql-42.6.0.jar"
        dest: "/bridge/postgresql-42.6.0.jar"

    - name: Copy files
      copy:
        src: '{{item}}'
        dest: '/bridge'
      loop:
        - ./Dockerfile
        - ./token
        - ./variables

    - name: Build Docker image for Bridge
      docker_image:
        name: "bridge_image"
        source: build
        build:
          path: "/bridge"

    - name: Run Bridge Container
      docker_container:
        name: "bridge"
        image: "bridge_image"
        env_file: "/bridge/variables"
        detach: true
